/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkpaint;
import bkpaint.Library;
import javax.swing.ImageIcon;

/**
 *
 * @author quochung17
 */
public class bkbkpaint extends javax.swing.JFrame  {
    /**
     * Creates new form bkbkpaint
     */
    public bkbkpaint() {
        initComponents();
    }
    public static boolean isUndo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DrawPanel = new bkpaint.DrawPanel();
        PaintApp = new bkpaint.PaintApp();
        Undobutton = new javax.swing.JButton();
        Redobutton = new javax.swing.JButton();
        ReplayVideo = new javax.swing.JButton();
        Librarys = new javax.swing.JButton();
        menuControl2 = new bkpaint.MenuControl();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BK Paint");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        setIconImage(new ImageIcon(getClass().getResource("icon/paint.png")).getImage());

        DrawPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 204, 241), 2));

        javax.swing.GroupLayout DrawPanelLayout = new javax.swing.GroupLayout(DrawPanel);
        DrawPanel.setLayout(DrawPanelLayout);
        DrawPanelLayout.setHorizontalGroup(
            DrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1658, Short.MAX_VALUE)
        );
        DrawPanelLayout.setVerticalGroup(
            DrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );

        Undobutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkpaint/icon/undo.png"))); // NOI18N
        Undobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndobuttonActionPerformed(evt);
            }
        });

        Redobutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkpaint/icon/redo.png"))); // NOI18N
        Redobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedobuttonActionPerformed(evt);
            }
        });

        ReplayVideo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ReplayVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkpaint/icon/replayvideo.png"))); // NOI18N
        ReplayVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplayVideoActionPerformed(evt);
            }
        });

        Librarys.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Librarys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkpaint/icon/library.png"))); // NOI18N
        Librarys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarysActionPerformed(evt);
            }
        });
        setJMenuBar(menuControl2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DrawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PaintApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Undobutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Redobutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReplayVideo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Librarys, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PaintApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Undobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Redobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReplayVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Librarys, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DrawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UndobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndobuttonActionPerformed
        // TODO add your handling code here:
        isUndo = true;
        bkbkpaint.DrawPanel.Undo();

    }//GEN-LAST:event_UndobuttonActionPerformed

    private void RedobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedobuttonActionPerformed
        // TODO add your handling code here:
        isUndo = false;
        bkbkpaint.DrawPanel.Undo();

    }//GEN-LAST:event_RedobuttonActionPerformed

    private void LibrarysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarysActionPerformed
         Library lib=new Library();
        lib.openimage();
    }//GEN-LAST:event_LibrarysActionPerformed

    private void ReplayVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplayVideoActionPerformed
        // TODO add your handling code here:
        new createRepVid();
    }//GEN-LAST:event_ReplayVideoActionPerformed

    /**
     * @param args the command line arguments
     */
//        @Override
//    public void run() {
//        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//        new bkbkpaint().setVisible(true);
//        
//    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
         bkbkpaint app= new bkbkpaint() ; 

         app.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static bkpaint.DrawPanel DrawPanel;
    private javax.swing.JButton Librarys;
    public static bkpaint.PaintApp PaintApp;
    private javax.swing.JButton Redobutton;
    private javax.swing.JButton ReplayVideo;
    private javax.swing.JButton Undobutton;
    private bkpaint.MenuControl menuControl2;
    // End of variables declaration//GEN-END:variables


}
